---
title: "In Class Template"
author: "Ethan C"
format: pdf
---

# 1. Set Up

## Packages

```{r}
#| label: packages

library(tidyverse)
library(here)
library(janitor)
library(snakecase)

#Wrap Axis Label
library(scales)

#reading .xlsx files
library(readxl)

# visualize missing data
library(naniar)

# visualizing
library(patchwork)
```

## Data 
```{r}
#| label: data

# taxnomic information
taxon_list <- read_csv(here("data", "taxon_list.csv"))

# aquatic invertebrates
aq_ins <- read_xlsx(
  here("data", "Aquatic Sampling Data-2026-03-10.xlsx"),
  sheet = "Aquatic Insects"
)

# site information
sites <- read_xlsx(
  here("data", "Aquatic Sampling Data-2026-03-10.xlsx"),
  sheet = "sites"
)

# water quality

water_quality <- read_xlsx(
  here("data", "Aquatic Sampling Data-2026-03-10.xlsx"),
  sheet = "Water Quality",
  na = c("", "n/a", "N/A", "over", "173+")
)

```


# 2. Cleaning

## `sites` object

Goal: createa a new object from `sites` that only includes NCOS sites

```{r}
#| label: ncos-sites

# creating new object from sites
ncos_sites <- sites %>% 
  # filering to only include sites at NCOS, sampled quarterly
  filter(sector == "NCOS" & sampling_frequency == "Quarterly")

```


